import {CustomTable} from '@/components/CustomTable';

export default function CarTable()  {
    return (
        <CustomTable list={[
                {
                        "id": 9,
                        "model": "Audi A4",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 10,
                        "model": "Audi A5",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 11,
                        "model": "Audi A5",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 12,
                        "model": "Audi A5",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 13,
                        "model": "Audi A5",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 14,
                        "model": "Audi A6",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 15,
                        "model": "Audi A6",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 16,
                        "model": "Audi A6",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 17,
                        "model": "Audi A6",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                },
                {
                        "id": 8,
                        "model": "Audi A6",
                        "brand": "Audi",
                        "doorNo": 4,
                        "registration": 2021,
                        "kilometers": 10000.00,
                        "purchasePrice": 35000.00,
                        "colour": "White",
                        "metallic": false,
                        "region": "South",
                        "emissionClass": "Euro 6",
                        "horsepower": 140.00,
                        "emissionSticker": "4 (Green)",
                        "fuelType": "Petrol",
                        "cubicCapacity": 1984.00,
                        "sellingPrice": 40000.00,
                        "lastUpdatedBy": 1
                }
        ]} tableType={'Car'}></CustomTable>
    );
}